### PR TITLE
Provisioning: added some more use cases to the dashboard

### PR DESCRIPTION
**Pull request by mckn**

### CODE REVIEW

**Comment by tolzhabayev** [comment]
Maybe set the countdown a bit further in the future? It will be outdated in a month :)

**Comment by mckn** [comment]
> Maybe set the countdown a bit further in the future? It will be outdated in a month :)

Done and done 🙏🏻

**Review by xnyo — APPROVED** [review]
Great work! LGTM  🎉

**Review by jackw — APPROVED** [review]
Awesome work on this @mckn . 🚀

**Pull request merged**
