### PR TITLE
add support for moment-timezone

### PR DESCRIPTION
**Pull request by bmagistro**
Addresses https://github.com/grafana/clock-panel/issues/8
This does not provide timezone support to the countdown version

Has a dependency on an update to moment-timezone and grafana.  Issues/Pull requests still being generated.

### CODE REVIEW

**Comment by torkelo** [comment]
This looks like a breaking change, removing option offsetFromUtcMinutes, so this will break a lot o dashboards for everyone upgrading which is not very good.

**Comment by bmagistro** [comment]
Yes it is.  Until you mentioned it now, the upgrade path hadn't even occurred to me.  Let me see if I can do something about it.  MIght not be the correct timezone but could get close (or at the very least same offset)

**Comment by bmagistro** [comment]
So I have a easy path to handle cock type (24/212/custom).  The timezone from previous offset is proving to be a little more difficult.  I was going to just add a custom zone for their entry but that depends on the utils lib from moment-timezone and I don't want to keep including things that shouldn't be needed longer term.  My current thinking is to just use the previously stored offsets if present and then when it is edited next they can select the correct timezone.  Thoughts?

**Comment by bmagistro** [comment]
With out additional feedback, upgrade path is as follows:
1) use previously defined clockType if new clockType has not been defined
2) if timezone is not defined, fall back to using previously defined offsetFromUtc, if offsets are also not defined, guess on the timezone which should be local time on your computer.

**Comment by daniellee** [comment]
Sorry about the delay. That sounds fine.

**Pull request closed without merging**
